### ISSUE TITLE
Will there be support to call deconz scenes?

### ISSUE THREAD

**Issue by vandalon** [andreypopov/node-red-contrib-deconz#5]
Or is it already there and am I blind? :)

**Comment by andreypopov** [comment]
if u need, I will add in next versions

**Comment by vandalon** [comment]
That would be awesome, thanks!

**Comment by drankard** [comment]
Any news on this ?

**Comment by andreypopov** [comment]
why do you use scenes, while you use node-red  ?

**Comment by vandalon** [comment]
Scènes are actually stored in the lights. Also its easier to call 1 one scene instead of setting brightness and color or colortemp for several lights at once. (Less clutter)

**Comment by hannemann** [comment]
Supporting scenes would work around a firmware bug in ikea tradfri bulbs. Currently it is not possible to change the brightness and color simultaneously within one request. But switching a scene does.

https://github.com/dresden-elektronik/deconz-rest-plugin/issues/894
https://www.reddit.com/r/tradfri/comments/au903n/firmware_bugs_in_ikea_bulbs/

**Comment by MrMiracles** [comment]
I made a few adjustments to @andreypopov files (out.html and out.js) to be able to send scenes, works perfect for me (Philips HUE and GLEDOPTO controller).

It is of course not as clean and nice as all the other stuff but it works. Something that would be nice is if it checked which scene ID would be valid. Because now you can add whatever ID you want and I don't know what will happen if you use a not existing one... Probably nothing but still...

[out.zip](https://github.com/andreypopov/node-red-contrib-deconz/files/3766504/out.zip)



What I did (see attachments):
out.html:
Line 110: added scene as an option

out.js:
Line 111: added scene as an option, parse payload as Int.
Line 146 - 149: added extra IF statement to be able to create the right URL for recalling scenes
Line 158: changed if-else statement to make sure no post data is set. 

All the love and thanks to @andreypopov he made it possible!

**Comment by andreypopov** [comment]
cool, thanks, I will check it

**Comment by andreypopov** [comment]
Added more friendly UI v1.1.0
 
![2019-10-28_21-02-23](https://user-images.githubusercontent.com/1624839/67704857-f58cd880-f9c6-11e9-86b3-4fad7e52a705.png)
![2019-10-28_20-33-33](https://user-images.githubusercontent.com/1624839/67704859-f6256f00-f9c6-11e9-9ed6-651e0902696c.png)

**Comment by MrMiracles** [comment]
great work! Thanks, you're the man!
